# Generated by Django 4.1.6 on 2023-03-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Timecreated',
            new_name='created',
        ),
    ]
